name: Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: find src include test -iregex '.*\.\(c\|h\|cpp\|hpp\|cc\|hh\|cxx\|hxx\)$' | xargs clang-format -n -Werror
    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install libboost-all-dev doctest-dev
    - name: Build and test
      run: mkdir build && cd build && cmake -DTESTING=yes .. && make && ctest
